#!/usr/bin/env bash
#
# lab_sync.sh — pull the latest course updates without losing your work.
#
# The course repo gets updated during the term (Makefile fixes, new exercises,
# corrected testbenches). The HDL source files you edit in the starter/ folders
# generally do NOT change upstream, so the safe way to grab updates is:
#
#     1. stash your local edits (including new, untracked files)
#     2. pull the latest commits
#     3. re-apply your edits on top
#
# This script does exactly that, with safety checks so your work is never lost:
# if step 3 hits a conflict, your changes stay saved in a git stash and the
# script tells you how to recover them.
#
# Usage:
#     scripts/lab_sync.sh              # sync the current branch
#     scripts/lab_sync.sh --rebase     # replay upstream under your commits (advanced)
#     scripts/lab_sync.sh -h | --help
#
set -euo pipefail

USE_REBASE=0
for arg in "$@"; do
  case "$arg" in
    --rebase) USE_REBASE=1 ;;
    -h|--help)
      sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'
      exit 0 ;;
    *)
      echo "lab_sync: unknown option '$arg' (try --help)" >&2
      exit 2 ;;
  esac
done

# Always operate from the repo root.
cd "$(git rev-parse --show-toplevel)"

BRANCH="$(git rev-parse --abbrev-ref HEAD)"
if [ "$BRANCH" = "HEAD" ]; then
  echo "lab_sync: you are in a detached HEAD state. Check out a branch first." >&2
  exit 1
fi

# Figure out where to pull from. Prefer the configured upstream; fall back to
# origin/<branch> if no upstream is set.
if UPSTREAM="$(git rev-parse --abbrev-ref --symbolic-full-name '@{upstream}' 2>/dev/null)"; then
  REMOTE="${UPSTREAM%%/*}"
  REMOTE_BRANCH="${UPSTREAM#*/}"
else
  REMOTE="origin"
  REMOTE_BRANCH="$BRANCH"
  echo "lab_sync: no upstream configured for '$BRANCH'; assuming $REMOTE/$REMOTE_BRANCH"
fi

echo "==> Syncing '$BRANCH' from $REMOTE/$REMOTE_BRANCH"

# --- fetch with a few retries for flaky networks ---------------------------
fetch_with_retry() {
  local delay=2 attempt=1
  while true; do
    if git fetch "$REMOTE" "$REMOTE_BRANCH"; then
      return 0
    fi
    if [ "$attempt" -ge 4 ]; then
      echo "lab_sync: 'git fetch' failed after $attempt attempts." >&2
      return 1
    fi
    echo "lab_sync: fetch failed, retrying in ${delay}s..." >&2
    sleep "$delay"
    delay=$((delay * 2))
    attempt=$((attempt + 1))
  done
}
fetch_with_retry

# --- normalise flake.lock --------------------------------------------------
# 'nix develop' frequently rewrites flake.lock (re-locking inputs / re-normalising
# the JSON) even when nothing meaningful changed. That incidental churn is what
# makes 'git stash' abort with "Entry 'flake.lock' not uptodate. Cannot merge."
# flake.lock is upstream-owned and fully reproducible, so discard any local
# changes to it and let the upstream version win. (Only touches the uncommitted
# working copy — committed history is untouched.)
#
# Only restore when HEAD actually contains a committed flake.lock; otherwise
# 'git checkout HEAD -- flake.lock' fails with "pathspec ... did not match"
# (e.g. a fresh checkout that doesn't track it yet, where nix just created it).
# In that case leave it for the normal stash path below.
if git cat-file -e HEAD:flake.lock 2>/dev/null \
   && ! git diff --quiet HEAD -- flake.lock; then
  echo "==> Discarding local flake.lock churn (regenerated by 'nix develop'; upstream version will be used)"
  git checkout HEAD -- flake.lock
fi

# --- stash local work (only if there is any) -------------------------------
# Refresh the index first. On freshly-checked-out trees (common in the lab
# containers) files can have stale stat info, which makes git think they're
# modified. That false positive makes 'git stash' abort with
# "Entry '...' not uptodate. Cannot merge." Re-stat'ing clears it. The command
# exits non-zero when there are genuinely modified files, which is fine here.
git update-index -q --refresh || true

STASHED=0
if [ -n "$(git status --porcelain)" ]; then
  echo "==> Stashing your local changes"
  git stash push --include-untracked --message "lab-sync $(date '+%Y-%m-%d %H:%M:%S')"
  STASHED=1
else
  echo "==> Working tree is clean — nothing to stash"
fi

# --- bring in upstream commits ---------------------------------------------
echo "==> Updating to $REMOTE/$REMOTE_BRANCH"
if [ "$USE_REBASE" -eq 1 ]; then
  git rebase "$REMOTE/$REMOTE_BRANCH"
else
  # Fast-forward only: the student's branch should just advance to upstream.
  # If it can't fast-forward (you have local commits that diverged), fall back
  # to a merge so nothing is silently dropped.
  if ! git merge --ff-only "$REMOTE/$REMOTE_BRANCH" 2>/dev/null; then
    echo "==> Branch has diverged from upstream; merging instead of fast-forward"
    git merge --no-edit "$REMOTE/$REMOTE_BRANCH"
  fi
fi

# --- re-apply the student's work -------------------------------------------
if [ "$STASHED" -eq 1 ]; then
  echo "==> Re-applying your local changes"
  if git stash pop; then
    echo "==> Done. Your changes are back on top of the latest course updates."
  else
    cat >&2 <<'MSG'

lab_sync: your changes conflicted with the update and are STILL SAVED.
          Nothing was lost. To recover:

            git status            # see which files conflict
            # edit the conflicted files to resolve the <<<< ==== >>>> markers
            git add <files>
            git stash drop        # once everything looks right

          Or, to throw away the pull and get back exactly what you had:

            git reset --hard      # discard the merge
            git stash pop         # restore your work

MSG
    exit 1
  fi
else
  echo "==> Done. You are up to date."
fi
